// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $.ajax("//raw.githubusercontent.com/jncornett/RecordParser/master/AbstractRegex/description.txt", {
      dataType: "text",
      crossDomain: true
    });
  });

}).call(this);
