// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $("#RecordParser").load("https://raw.githubusercontent.com/jncornett/RecordParser/master/AbstractRegex/description.txt");
  });

}).call(this);
